game.scene.add('scene1',scene1)
game.scene.add('scene2',scene2)
game.scene.add('scene3',scene3)
game.scene.add('scene4',scene4)
game.scene.add('scene5',scene5)
game.scene.add('scene6',scene6)
game.scene.add('scene7',scene7)
game.scene.add('scene8',scene8)
game.scene.add('scene9',scene9)
game.scene.add('scene10',scene10)
game.scene.add('scene11',scene11)
game.scene.add('scene12',scene12)
game.scene.add('scene13',scene13)
game.scene.add('scene14',scene14)
game.scene.add('scene15',scene15)

game.scene.add('scene_end2',scene_end2)
game.scene.add('scene_end1',scene_end1)

game.scene.add('gamescene', gamescene)
game.scene.start('scene1')